TARpe22ShopMyyrsepp/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;

namespace TARpe22ShopMyyrsepp.Controllers
{
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TARpe22ShopMyyrsepp/Controllers/RealEstatesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Metrics;
using System.Drawing;
using System.Net;
using TARpe22ShopMyyrsepp.Core.Dto;
using TARpe22ShopMyyrsepp.Core.ServiceInterface;
using TARpe22ShopMyyrsepp.Models.RealEstate;
using TARpe22ShopMyyrsepp.Core.Dto;
using TARpe22ShopMyyrsepp.Core.ServiceInterface;
using TARpe22ShopMyyrsepp.Data;
using TARpe22ShopMyyrsepp.Models.RealEstate;

namespace TARpe22ShopMyyrsepp.Controllers
{
    public class RealEstatesController : Controller
    {
        private readonly IRealEstatesServices _realEstatesServices;
        private readonly TARpe22ShopMyyrseppContext _context;
        private readonly IFilesServices _filesServices;
        public RealEstatesController(IRealEstatesServices realEstatesServices, TARpe22ShopMyyrseppContext context, IFilesServices filesServices)
        {
            _realEstatesServices = realEstatesServices;
            _context = context;
            _filesServices = filesServices;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.RealEstates
                .OrderByDescending(y => y.CreatedAt)
                .Select(x => new RealEstateViewModel
                {
                    //{ return (Country + ", " + County + ", " + City + ", " + Address); }
                    Id = x.Id,
                    Location = x.Country + ", " + x.County + ", " + x.City + ", " + x.Address,
                    SquareMeters = x.SquareMeters,
                    RoomCount = x.RoomCount,
                    Price = x.Price,
                    IsPropertySold = x.IsPropertySold,
                });
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel vm = new();
            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = Guid.NewGuid(),
                Type = vm.Type,
                ListingDescription = vm.ListingDescription,
                Address = vm.Address,
                County = vm.County,
                Country = vm.Country,
                City = vm.City,
                PostalCode = vm.PostalCode,
                ContactPhone = vm.ContactPhone,
                ContactFax = vm.ContactFax,
                SquareMeters = vm.SquareMeters,
                Floor = vm.Floor,
                FloorCount = vm.FloorCount,
                Price = vm.Price,
                RoomCount = vm.RoomCount,
                BedroomCount = vm.BedroomCount,
                BathroomCount = vm.BathroomCount,
                WhenEstateListedAt = vm.WhenEstateListedAt,
                IsPropertySold = vm.IsPropertySold,
                DoesHaveSwimmingPool = vm.DoesHaveSwimmingPool,
                BuiltAt = vm.BuiltAt,
                CreatedAt = DateTime.Now,
                ModifiedAt = DateTime.Now,
                Files = vm.Files,
                FileToApiDtos = vm.FileToApiViewModels
                .Select(x => new FileToApiDto
                {
                    Id = x.ImageId,
                    ExistingFilePath = x.FilePath,
                    RealEstateId = x.RealEstateId,
                }).ToArray()
            };
            var result = await _realEstatesServices.Create(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", vm);

        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);
            if (realEstate == null)
            {
                return NotFound();
            }
            var images = await _context.FilesToApi
                .Where(x => x.RealEstateId == id)
                .Select(y => new FileToApiViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageId = y.Id
                }).ToArrayAsync();
            var vm = new RealEstateCreateUpdateViewModel();
            vm.Id = realEstate.Id;
            vm.Type = realEstate.Type;
            vm.ListingDescription = realEstate.ListingDescription;
            vm.Address = realEstate.Address;
            vm.County = realEstate.County;
            vm.Country = realEstate.Country;
            vm.City = realEstate.City;
            vm.PostalCode = realEstate.PostalCode;
            vm.ContactPhone = realEstate.ContactPhone;
            vm.ContactFax = realEstate.ContactFax;
            vm.SquareMeters = realEstate.SquareMeters;
            vm.Floor = realEstate.Floor;
            vm.FloorCount = realEstate.FloorCount;
            vm.Price = realEstate.Price;
            vm.RoomCount = realEstate.RoomCount;
            vm.BedroomCount = realEstate.BedroomCount;
            vm.BathroomCount = realEstate.BathroomCount;
            vm.WhenEstateListedAt = realEstate.WhenEstateListedAt;
            vm.IsPropertySold = realEstate.IsPropertySold;
            vm.DoesHaveSwimmingPool = realEstate.DoesHaveSwimmingPool;
            vm.BuiltAt = realEstate.BuiltAt;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = DateTime.Now;
            vm.FileToApiViewModels.AddRange(images);

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = (Guid)vm.Id,
                Type = vm.Type,
                ListingDescription = vm.ListingDescription,
                Address = vm.Address,
                County = vm.County,
                Country = vm.Country,
                City = vm.City,
                PostalCode = vm.PostalCode,
                ContactPhone = vm.ContactPhone,
                ContactFax = vm.ContactFax,
                SquareMeters = vm.SquareMeters,
                Floor = vm.Floor,
                FloorCount = vm.FloorCount,
                Price = vm.Price,
                RoomCount = vm.RoomCount,
                BedroomCount = vm.BedroomCount,
                BathroomCount = vm.BathroomCount,
                WhenEstateListedAt = vm.WhenEstateListedAt,
                IsPropertySold = vm.IsPropertySold,
                DoesHaveSwimmingPool = vm.DoesHaveSwimmingPool,
                BuiltAt = vm.BuiltAt,
                CreatedAt = DateTime.Now,
                ModifiedAt = DateTime.Now,
                Files = vm.Files,
                FileToApiDtos = vm.FileToApiViewModels
                .Select(x => new FileToApiDto
                {
                    Id = x.ImageId,
                    ExistingFilePath = x.FilePath,
                    RealEstateId = x.RealEstateId,
                }).ToArray()
            };
            var result = await _realEstatesServices.Update(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);
            if (realEstate == null)
            {
                return NotFound();
            }
            var images = await _context.FilesToApi
            .Where(x => x.RealEstateId == id)
            .Select(y => new FileToApiViewModel
            {
                FilePath = y.ExistingFilePath,
                ImageId = y.Id
            }).ToArrayAsync();
            var vm = new RealEstateDetailsViewModel(); //todo: details viewmodel
            vm.Id = realEstate.Id;
            vm.Type = realEstate.Type;
            vm.ListingDescription = realEstate.ListingDescription;
            vm.Address = realEstate.Address;
            vm.County = realEstate.County;
            vm.Country = realEstate.Country;
            vm.City = realEstate.City;
            vm.PostalCode = realEstate.PostalCode;
            vm.ContactPhone = realEstate.ContactPhone;
            vm.ContactFax = realEstate.ContactFax;
            vm.SquareMeters = realEstate.SquareMeters;
            vm.Floor = realEstate.Floor;
            vm.FloorCount = realEstate.FloorCount;
            vm.Price = realEstate.Price;
            vm.RoomCount = realEstate.RoomCount;
            vm.BedroomCount = realEstate.BedroomCount;
            vm.BathroomCount = realEstate.BathroomCount;
            vm.WhenEstateListedAt = realEstate.WhenEstateListedAt;
            vm.IsPropertySold = realEstate.IsPropertySold;
            vm.DoesHaveSwimmingPool = realEstate.DoesHaveSwimmingPool;
            vm.BuiltAt = realEstate.BuiltAt;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.FileToApiViewModels.AddRange(images);

            return View(vm);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }
            var images = await _context.FilesToApi
            .Where(x => x.RealEstateId == id)
            .Select(y => new FileToApiViewModel
            {
                FilePath = y.ExistingFilePath,
                ImageId = y.Id
            }).ToArrayAsync();
            var vm = new RealEstateDeleteViewModel();
            vm.Id = realEstate.Id;
            vm.Type = realEstate.Type;
            vm.ListingDescription = realEstate.ListingDescription;
            vm.Address = realEstate.Address;
            vm.County = realEstate.County;
            vm.Country = realEstate.Country;

TARpe22ShopMyyrsepp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TARpe22ShopMyyrsepp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TARpe22ShopMyyrsepp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TARpe22ShopMyyrsepp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spaceships" asp-action="Index">Spaceship</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RealEstates" asp-action="Index">Real Estate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForecasts" asp-action="Index">Weather Forecasts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForecasts2" asp-action="Index">Weather Forecasts OpenWeather</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TARpe22ShopMyyrsepp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>